import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import ScrollToTop from "./components/ScrollToTop";
import "./globals.css";
import "toastify-js/src/toastify.css";
import { HomePageProvider } from "./context/HomePageContext";
import { DefaultLayout } from "./layouts";

const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ScrollToTop />
        <HomePageProvider>
          <DefaultLayout>{children}</DefaultLayout>
        </HomePageProvider>
      </body>
    </html>
  );
}
